name: prashna_pooja_app
publish_to: 'none'
description: A Flutter app with Prashna (audio) and Pooja (video) order submissions.
version: 1.1.0+3
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.3
  http: ^1.2.2
  record: ^6.1.2
  camera: ^0.11.0+2
  file_picker: ^8.1.2
  permission_handler: ^11.3.1
  intl: ^0.20.2
  video_player: ^2.9.2
  audioplayers: ^6.0.0
  path_provider: ^2.1.4
  provider: ^6.1.5+1
  flutter_animate: ^4.5.0 
  google_fonts: ^6.2.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
